services:
  db:
    image: postgres:16.0
    container_name: monitoriadb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: monitoriapgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_USER: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"    # http://localhost:8081 #admin@admin.com senha: admin
    depends_on:
      - db
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: monitoriamongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: monitoriamongoexpress
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: monitoriaredis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data: